# Part I: Importing Libraries and Data

In [55]:
import csv
import pandas as pd
import numpy as np

In [56]:
pull_req_data = pd.read_csv('./preprocessed_data.csv')

In [57]:
pull_req_data.head(n=10)

slug  gh_team_size  commits  git_num_commits  gh_num_issue_comments  \
0  aws/aws-cli             2        1                1                      0   
1  aws/aws-cli             2        1                1                      0   
2  aws/aws-cli             2        1                1                      0   
3  aws/aws-cli             2        1                1                      0   
4  aws/aws-cli             2        1                1                      0   
5  aws/aws-cli             2        1                1                      0   
6  aws/aws-cli             2        1                1                      0   
7  aws/aws-cli             2        1                1                      0   
8  aws/aws-cli             2        1                1                      0   
9  aws/aws-cli             2        1                1                      1   

   general_comments  num_commit_comments  pull_req_comments  \
0                11                    0                  2   
1                11                    0                  2   
2                11                    0                  2   
3                11                    0                  2   
4                11                    0                  2   
5                11                    0                  2   
6                11                    0                  2   
7                11                    0                  2   
8                11                    0                  2   
9                 0                    0                  0   

   gh_num_pr_comments  additions        ...         title_len  desc_len  \
0                   0         32        ...                67        70   
1                   0         32        ...                67        70   
2                   0         32        ...                67        70   
3                   0         32        ...                67        70   
4                   0         32        ...                67        70   
5                   0         32        ...                67        70   
6                   0         32        ...                67        70   
7                   0         32        ...                67        70   
8                   0         32        ...                67        70   
9                  15        105        ...                61         0   

   gh_description_complexity  git_num_committers     Id   state  merged  \
0                         18                   1  37759    open   False   
1                          6                   1  37759    open   False   
2                         45                   1  37759    open   False   
3                          3                   1  37759    open   False   
4                         77                   1  37759    open   False   
5                         29                   1  37759    open   False   
6                         29                   1  37759    open   False   
7                          5                   1  37759    open   False   
8                          8                   1  37759    open   False   
9                         54                   1  37154  closed    True   

                           merge_commit_sha  delta_mins_merge  \
0  3c8f76d8930869cb366034b3b0f4aad022a068cc            -1.000   
1  3c8f76d8930869cb366034b3b0f4aad022a068cc            -1.000   
2  3c8f76d8930869cb366034b3b0f4aad022a068cc            -1.000   
3  3c8f76d8930869cb366034b3b0f4aad022a068cc            -1.000   
4  3c8f76d8930869cb366034b3b0f4aad022a068cc            -1.000   
5  3c8f76d8930869cb366034b3b0f4aad022a068cc            -1.000   
6  3c8f76d8930869cb366034b3b0f4aad022a068cc            -1.000   
7  3c8f76d8930869cb366034b3b0f4aad022a068cc            -1.000   
8  3c8f76d8930869cb366034b3b0f4aad022a068cc            -1.000   
9  9ff89d35c64f330998cbc92e269b84188730a3e3           822.967   

   delta_mins_close  
0            -1.000  
1           

In [58]:
pull_req_data.shape

(16281, 39)

# Part II: Basic Statistics

In [59]:
pull_req_data.describe()

gh_team_size       commits  git_num_commits  gh_num_issue_comments  \
count  16281.000000  16281.000000     16281.000000           16281.000000   
mean      29.163319      3.402678         1.775935               0.787114   
std       19.137092     24.206409         3.143014               2.005186   
min        1.000000      0.000000         1.000000               0.000000   
25%       12.000000      1.000000         1.000000               0.000000   
50%       26.000000      1.000000         1.000000               0.000000   
75%       42.000000      2.000000         2.000000               1.000000   
max       88.000000   1887.000000       151.000000              35.000000   

       general_comments  num_commit_comments  pull_req_comments  \
count      16281.000000         16281.000000       16281.000000   
mean           4.355936             0.740311           1.533075   
std            7.631124             4.060235           5.129924   
min            0.000000             0.000000           0.000000   
25%            1.000000             0.000000           0.000000   
50%            2.000000             0.000000           0.000000   
75%            5.000000             0.000000           1.000000   
max          136.000000           167.000000         128.000000   

       gh_num_pr_comments      additions     deletions        ...         \
count        16281.000000   16281.000000  16281.000000        ...          
mean             0.716971     269.301394     75.960936        ...          
std              3.213376    1757.315670    545.112344        ...          
min              0.000000       0.000000      0.000000        ...          
25%              0.000000       4.000000      1.000000        ...          
50%              0.000000      19.000000      4.000000        ...          
75%              0.000000      91.000000     20.000000        ...          
max             90.000000  116015.000000  43469.000000        ...          

       gh_asserts_cases_per_kloc  gh_by_core_team_member     title_len  \
count               16281.000000            16281.000000  16281.000000   
mean                  253.379296                0.884589     43.547448   
std                  1326.439033                0.319527     17.593603   
min                     0.000000                0.000000      3.000000   
25%                    41.877544                1.000000     31.000000   
50%                   147.863386                1.000000     42.000000   
75%                   224.488655                1.000000     55.000000   
max                 87000.000000                1.000000    180.000000   

           desc_len  gh_description_complexity  git_num_committers  \
count  16281.000000               16281.000000        16281.000000   
mean     349.844543                  51.857441            1.182974   
std      620.914258                 196.907239            0.414118   
min        0.000000                   1.000000            0.000000   
25%       22.000000                   9.000000            1.000000   
50%      120.000000                  23.000000            1.000000   
75%      373.000000                  49.000000            1.000000   
max    10326.000000                7476.000000            6.000000   

                 Id    merged  delta_mins_merge  delta_mins_close  
count  16281.000000     16281      16281.000000      16281.000000  
mean   43430.946072  0.672563        351.960456        491.967883  
std    22983.449713  0.469293        467.821023        487.672914  
min     3763.000000     False         -1.000000         -1.000000  
25%    25391.000000         0         -1.000000         42.516700  
50%    44307.000000         1         74.783300        292.333000  
75%    59193.000000         1        713.917000        938.117000  
max    81785.000000      True       1439.200000       1439.200000  

[8 rows x 36 columns]

In [60]:
total_pull_req = len(pull_req_data)
pull_reqs_accepted = len(pull_req_data[pull_req_data["merged"] == True])
print 'Total pull requests in our given data = ', total_pull_req
print 'Accepted pull requests = ', pull_reqs_accepted
print 'Percentage of Accepted pull requests = %.2f' % ((float(pull_reqs_accepted)/float(total_pull_req)) * 100)
#perc_accepted = len(pulllen(pull_req_data[pull_req_data["merged"] == True])

Total pull requests in our given data =  16281
Accepted pull requests =  10950
Percentage of Accepted pull requests = 67.26


# Preprocessing (Split Target Feature and Columns)

In [61]:
def convertToNonNegatives(x):
    if x < 0:
        return 0
    else:
        return x

In [65]:
pull_req_data['delta_mins_merge'] = pull_req_data['delta_mins_merge'].apply(convertToNonNegatives)
pull_req_data['delta_mins_close'] = pull_req_data['delta_mins_close'].apply(convertToNonNegatives)

In [66]:
Y = np.array(pull_req_data['merged'].apply(int))
Y
#dropped_features = pull_req_data.drop(['Id', 'state', 'merged', 'merge_commit_sha'], axis=1)
#dropped_features

array([0, 0, 0, ..., 0, 1, 0])

In [67]:
dropped_features = pull_req_data.drop(['slug', 'Id', 'state', 'merged', 'merge_commit_sha'], axis=1)
X = dropped_features.as_matrix().astype(np.float)
X.shape

(16281, 34)

# Part III: Feature Selection

In [75]:
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE
from sklearn import datasets
from sklearn import metrics
from sklearn.ensemble import ExtraTreesClassifier

In [78]:
# create a base classifier used to evaluate a subset of attributes
model = LogisticRegression()
# create the RFE model and select 3 attributes
rfe = RFE(model, 5)
rfe = rfe.fit(X, Y)
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)
features = rfe.transform(X)
features[0:5,:]

[False False False False  True False False False False False False False
 False False False False False False False False False False False False
 False False False  True False False False  True  True  True]
[19  4 15 23  1  8  2 14 13 11 28 18 27 24 10 21 16  5  3 17  7 12 20 30 29
 26 25  1  6  9 22  1  1  1]


array([[ 11.,   0.,   1.,   0.,   0.],
       [ 11.,   1.,   1.,   0.,   0.],
       [ 11.,   1.,   1.,   0.,   0.],
       [ 11.,   1.,   1.,   0.,   0.],
       [ 11.,   1.,   1.,   0.,   0.]])

In [76]:
# fit an Extra Trees model to the data
model = ExtraTreesClassifier()
model.fit(X, Y)
# display the relative importance of each attribute
print(model.feature_importances_)

[  8.22729750e-03   1.79995034e-02   2.39065023e-03   2.97571671e-03
   4.27939582e-02   2.92565534e-03   1.01245876e-02   2.40887998e-03
   2.04835182e-02   1.33431565e-02   1.39709540e-02   1.61868611e-02
   3.22178723e-03   3.39110517e-03   2.94126800e-03   1.77702680e-03
   3.83677820e-03   1.36467122e-04   7.80739160e-04   3.33699857e-03
   2.50962534e-03   2.81052139e-03   4.68666239e-03   1.01081343e-02
   6.48829031e-03   5.95089372e-03   5.02551097e-03   2.59063672e-03
   1.87969104e-02   3.41289157e-02   7.41127771e-03   2.40325574e-03
   5.84383735e-01   1.39452721e-01]


In [69]:
X_new = SelectKBest(chi2, k=5).fit_transform(X, Y)
X_new.shape

(16281, 5)

In [70]:
X_new

array([[  3.20000000e+01,   3.50000000e+01,   1.17700000e+03,
          7.00000000e+01,   0.00000000e+00],
       [  3.20000000e+01,   3.50000000e+01,   4.06000000e+02,
          7.00000000e+01,   0.00000000e+00],
       [  3.20000000e+01,   3.50000000e+01,   9.90000000e+01,
          7.00000000e+01,   0.00000000e+00],
       ..., 
       [  1.60000000e+01,   3.80000000e+01,   5.08260000e+04,
          1.47000000e+02,   0.00000000e+00],
       [  3.00000000e+01,   4.70000000e+01,   5.69057000e+05,
          1.20000000e+01,   9.80133000e+02],
       [  1.60000000e+01,   3.80000000e+01,   1.56050000e+05,
          1.47000000e+02,   0.00000000e+00]])